config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to =>"homes#top"
  resources :users, only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: :index do
      collection do
        delete :destroy_all
      end
    end

  end

  resources :posts, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :recipes, only: [:new,:show,:edit,:update,:create,:destroy]
  end

  get 'search' => 'posts#search'


  resources :genres, only: [:show]




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_genres, dependent: :destroy
  has_many :posts, through: :post_genres
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @genres = @genre.posts.page(params[:page]).per(8)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_genre.html.erb
<h5 class="ml-4 mt-4 col-2 light">ジャンル検索</h5>
<div class="row ml-5 mr-5">
  <% genres.each do |genre| %>
    <%= link_to genre_path(genre.id) do %>
      <p class="ml-3 badge badge-pill badge-primary light3"><%= genre.genre_name %></p>
    <% end %>
  <% end %>
</div>

app/views/genres/show.html.erb
<div class="container py-2">
  <div class="row">
    <h1 class="font-weight-bold ml-4 light2">
      <%=@genre.genre_name %>一覧
    </h1>
    <h3 class="light2 d-flex align-items-end">
      (<%= @genre.posts.count %>件)
    </h3>
  </div>
  <div class="row">
    <% @genre.posts.each do |post| %>
      <div class="col-6">
        <div class="card mx-auto p-4 shadow-lg mt-5 w-90 border-radius: 300px light">
          <%= link_to post_path(post.id) do %>
            <%= image_tag post.get_post_image, class:"card-img-top index-img" %>
          <% end %>

          <div class="card-body p-1">
            <div class="row">
              <div class="col-2">
                <%= image_tag post.user.get_user_image, size: "50x50" %>
                <%= post.user.name %>
              </div>
              <div class="col-8">
                <p class="card-title">
                  <%= link_to(post_path(post.id), class:"text-dark") do %>
                    <div class="font1"><%= post.post_name %></div>
                  <% end %>
                </p>
              </div>

              <div class="col-2 pl-2 pr-0 mt-2">
                <%#いいね機能%>
                <% if post.favorited?(current_user) %>
                  <%#すでにいいねしている場合%>
                  <%= link_to post_favorites_path(post.id), method: :delete do %>
                    いいね♥<%= post.favorites.count %>
                  <% end %>
                <% else %>
                  <%#いいねしていない場合%>
                  <%= link_to post_favorites_path(post.id), method: :post do %>
                    いいね♡<%= post.favorites.count %>
                  <% end %>
                <% end %>
                <p><%= link_to "コメント#{post.comments.count}", post_path(post.id) %></p>
              </div>
            </div>

            <div class="row mt-2">
              <div class="col-4 font">
                <%= post.recipe_status %>
              </div>
              <div class="col-4 font">
                製作時間<%= post.cooking_time %>分
              </div>
              <div class="col-4 font">
                製作金額<%= post.cooking_cost %>円
              </div>
            </div>

            <div class="row mt-3">
              <% post.genres.each do |genre| %>
                <%= link_to genre_path(genre.id) do %>
                  <p class="badge badge-pill badge-primary light3 ml-3"><%= genre.genre_name %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="mt-4">
    <%= paginate @genres %>
  </div>
</div>