config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to =>"homes#top"
  resources :users, only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: :index do
      collection do
        delete :destroy_all
      end
    end

  end

  resources :posts, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :recipes, only: [:new,:show,:edit,:update,:create,:destroy]
  end

  get 'search' => 'posts#search'


  resources :genres, only: [:show]




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #プロフィールイメージ
  has_one_attached :user_image

  has_many :posts, dependent: :destroy
  #いいね機能
  has_many :favorites, dependent: :destroy
  #コメント機能
  has_many :comments, dependent: :destroy
  #フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create

  before_save :attach_default_image, unless: :user_image_attached?

  #フォローする
  def follow(user_id)
    self.relationships.create!(followed_id: user_id)
  end
  #フォロー解除
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    self.followings.include?(user)
  end

  #プロフィールイメージ
  def get_user_image
    user_image.variant(resize_to_limit: [300, 300]).processed
  end

  #フォロー時の通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  private

  def user_image_attached?
    user_image.attached?
  end

  def attach_default_image
    file_path = Rails.root.join('app/assets/images/no_image1.jpg')
    user_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(@user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end



  def user_params
    params.require(:user).permit(:name, :introduction, :user_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5 mb-4">
      <h2 class="text-center light mt-5 ml-5 col-8">プロフィール編集</h2>
    </div>
  </div>
  <% if @user.errors.any? %>
    <%= @user.errors.count %>件のエラーが発生しました
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row">
    <div class="col-10 mb-3 offset-2">
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group col-xs-9 mt-3">
          <%= f.label :プロフィール画像, class: "col-sm-3 light" %>
          <%= f.file_field :user_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="form-group col-xs-9 mt-5">
          <%= f.label :ニックネーム, class: "col-sm-3 light" %>
          <%= f.text_field :name, autofocus: true %>
        </div>
         <div class="form-group col-xs-9 mt-5">
            <%= f.label :自己紹介, class: "col-sm-3 align-top light" %>
            <%= f.text_area :introduction, autofocus: true, class: "col-sm-6 p-1", rows:"5" %>
        </div>
        <div class="row">
          <div class="col-3"></div>
          <div class="form-group col-8 mx-auto">
            <%= f.submit "変更を保存", class: "btn btn-success col-sm-2" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="d-flex justify-content-center">
  <div class="card w-100 light4 pb-5">
    <div class="row col-12 pt-5">
      <div class="col-3 pl-5">
        <%= image_tag @user.get_user_image, class: "user-img1" %>
        <% if @user == current_user %>
          <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
        <% else %>
          <% if current_user.following?(@user) %>
            <%=  link_to 'フォロー外す', user_relationships_path(user_id: @user.id), class: "btn btn-secondary", method: :delete %>
          <% else %>
            <%= link_to 'フォローする', user_relationships_path(user_id: @user.id),  class: "btn btn-success", method: :post %>
          <% end %>
        <% end %>
      </div>

      <div class="col-6 mt-5">
        <p class="mb-0">ユーザー名</p>
        <h3 style="background-color:rgba(255,255,255,0.6);">
          <%= @user.name %>
        </h3>
        <p class="mb-0 mt-4">紹介</p>
        <h5 class="text-break h-50", style="background-color:rgba(255,255,255,0.6);">
          <%= @user.introduction%>
        </h5>
      </div>

      <div class="col-3 mt-5 pl-5">
        <p>
          フォロー数
          <%= link_to user_followings_path(@user.id) do %>
            <%= @user.followings.count %>
          <% end %>
        </p>
        <p>
          フォロワー数
          <%= link_to user_followers_path(@user.id) do %>
            <%= @user.followers.count %>
          <% end %>
        </p>
        <% if @user == current_user %>
          <p class="btn btn-primary">
            <%= link_to "お知らせ", user_notifications_path(current_user.id), class: 'text-light' %>
            <% if unchecked_notifications.any? %>
              <div class="fa fa-circle mt-2 ml-2 pt-1" style="color: gold;"></div>
            <% end %>
          </p></br>
          <p class="btn btn-primary ">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-light' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'posts/list', posts: @posts %>