config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to =>"homes#top"
  resources :users, only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: :index do
      collection do
        delete :destroy_all
      end
    end

  end

  resources :posts, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :recipes, only: [:new,:show,:edit,:update,:create,:destroy]
  end

  get 'search' => 'posts#search'


  resources :genres, only: [:show]




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_genres, dependent: :destroy
  has_many :genres, through: :post_genres
  has_many :notifications, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :meterials, dependent: :destroy
  accepts_nested_attributes_for :recipes, :meterials, allow_destroy: true

  enum recipe_status: { レシピあり: 0, レシピなし: 1 }

  validates :post_name, presence: true
  validates :post_image, presence: true

  before_save :attach_default_image, unless: :post_image_attached?

  #いいね
  def favorited?(user)
     favorites.where(user_id: user.id).exists?
  end

  #投稿画像
  def get_post_image
    post_image.variant(resize_to_limit: [500, 500]).processed
  end

  #通知機能
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "favorited"
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end

    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )

    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  private

  def post_image_attached?
    post_image.attached?
  end

  def attach_default_image
    file_path = Rails.root.join('app/assets/images/no_image1.jpg')
    post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      @genre_ids = params[:post][:genre_ids]
      @genre_ids.each do |genre_id|
        if  genre_id != ""
          postgenre = PostGenre.new(post_id: @post.id, genre_id: genre_id.to_i)
          postgenre.save
        end
      end
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @genre = @post.post_genre_ids
    @comment = Comment.new
  end

  def index
    @posts = Post.page(params[:page]).per(8)
    @genres = Genre.all
    @posts = @posts.where('post_name LIKE?', "%#{params[:search]}%") if params[:search].present?
  end


  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render "edit"
    else
      redirect_to post_path(@post.id)
    end
  end


  def update
    @post = Post.find(params[:id])
    @post.user_id = current_user.id
    #アップデートが成功した場合
    if  @post.update(post_params)
    #タグを一度削除
      @post.post_genres.delete_all
    #再度タグ追加
      @genre_ids = params[:post][:genre_ids]
      @genre_ids.each do |genre_id|
      if  genre_id != ""
        postgenre = PostGenre.new(post_id: @post.id, genre_id: genre_id.to_i)
        postgenre.save
      end
    end
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to '/posts'
  end

  private
  def post_params
    params.require(:post).permit(:post_name,:post_introduction, :cooking_time, :cooking_cost, :recipe_status, :post_image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_list.html.erb
<div class="container py-2">
  <div class="row">
    <% posts.each do |post| %>
      <div class="col-6">
        <div class="card mx-auto p-4 shadow-lg mt-5 w-90 border-radius: 300px light">
          <%= link_to post_path(post.id) do %>
            <%= image_tag post.get_post_image, class:"card-img-top index-img" %>
          <% end %>

          <div class="card-body p-1 ">
            <div class="row">
              <div class="col-2">
                <%= image_tag post.user.get_user_image, size: "50x50" %>
                <%= post.user.name %>
              </div>
              <div class="col-8">
                <p class="card-title">
                  <%= link_to(post_path(post.id), class:"text-dark") do %>
                    <div class="font1"><%= post.post_name %></div>
                  <% end %>
                </p>
              </div>
              <div class="col-2 pl-2 pr-0 mt-2">
                <div id="favorite_btn_<%= post.id %>">
                  <%= render 'favorites/favorite', post: post %>
                </div>
                <div><%= link_to "コメント#{post.comments.count}", post_path(post.id) %></div>
              </div>
            </div>

            <div class="row mt-2">
              <div class="col-4 font">
                <%= post.recipe_status %>
              </div>
              <div class="col-4 font">
                製作時間<%= post.cooking_time %>分
              </div>
              <div class="col-4 font">
                製作金額<%= post.cooking_cost %>円
              </div>
            </div>

            <div class="row mt-3">
              <% post.genres.each do |genre| %>
                <%= link_to genre_path(genre.id) do %>
                  <p class="badge badge-pill badge-primary light3 ml-3"><%= genre.genre_name %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="mt-4">
    <%= paginate posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mb-5">
      <h2 class="text-center light2 mt-5 ml-5 col-8">投稿編集</h2>
    </div>
  </div>

  <%#エラー文%>
  <% if @post.errors.any? %>
    <%= @post.errors.count %>件のエラーが発生しました
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row">
    <div class="col-10 mb-5 offset-2">
      <%= form_with model: @post, url: post_path, local: true do |f| %>
        <form>
          <div class="form-group col-xs-9">
            <%= f.label :投稿画像, class: "col-sm-2 light" %>
            <%= f.file_field :post_image, accept: "image/*" %>
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :名称, class: "col-sm-2 light" %>
            <%= f.text_field :post_name, placeholder: "名称", class: "col-sm-6 p-1" %>
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :紹介, class: "col-sm-2 align-top light" %>
            <%= f.text_area :post_introduction, placeholder: "ここに説明文を記述します", class: "col-sm-6 p-1", rows:"5" %>
          </div>
          <div class="form-group col-xs-9">
            <div>
              <%= f.label :ジャンル, class: "col-sm-2 light" %>
            </div>
            <div class="col-11 ml-5 light2">
              <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :genre_name %>
            </div>
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :製作時間, class: "col-sm-3 light mr-3" %>
            <%= f.text_field :cooking_time, placeholder: "00", class: "text-center col-1 ml-5" %>分
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :製作金額, class: "col-sm-3 light mr-3" %>
            <%= f.text_field :cooking_cost, placeholder: "00", class: "text-center col-1 ml-5" %>円
          </div>
          <div class="form-group col-xs-9">
              <%= f.label :レシピの有無, class: "col-sm-2 light" %>
              <%= f.radio_button :recipe_status, :レシピあり, checked: "checked", class: "ml-5" %>
              <%= f.label :recipe_status, "レシピあり" %>
              <%= f.radio_button :recipe_status, :レシピなし, class: "ml-4" %>
              <%= f.label :recipe_status, "レシピなし" %>
          </div>
          <div class="row">
            <div class="col-3"></div>
            <div class="form-group col-8 mx-auto">
              <%= f.submit "変更を保存", class: "btn btn-success col-sm-2" %>
            </div>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <%#検索フォーム %>
  <div class="search-form">
    <%= form_with url: posts_path, method: :get, local: true do |f| %>
      <h5 class="ml-4 mt-3 col-2 light">投稿検索</h5>
      <div class="form-inline">
        <%= f.text_field :search, class:"ml-5" %>
        <%= f.submit "検索", name: nil %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12">
      <%= render "genres/genre", genres: @genres %>
    </div>
   </div>
   <div class="row">
    <div class="col-12">
      <%= render 'list', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mb-5">
      <h2 class="text-center light2 mt-5 ml-5 col-8">新規投稿</h2>
    </div>
  </div>

  <%#エラー文%>
  <% if @post.errors.any? %>
    <%= @post.errors.count %>件のエラーが発生しました
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row">
    <div class="col-10 mb-5 offset-2">
      <%= form_with model: @post, url: posts_path, local: true do |f| %>
        <form>
          <div class="form-group col-xs-9">
            <%= f.label :投稿画像, class: "col-sm-2 light" %>
            <%= f.file_field :post_image, accept: "image/*" %>
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :名称, class: "col-sm-2 light" %>
            <%= f.text_field :post_name, placeholder: "名称", class: "col-sm-6 p-1" %>
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :紹介, class: "col-sm-2 align-top light" %>
            <%= f.text_area :post_introduction, placeholder: "ここに説明文を記述します", class: "col-sm-6 p-1", rows:"5" %>
          </div>
          <div class="form-group col-xs-9">
            <div>
              <%= f.label :ジャンル, class: "col-sm-2 light" %>
            </div>
            <div class="col-11 ml-5 light2">
              <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :genre_name %>
            </div>
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :製作時間, class: "col-sm-3 light mr-5" %>
            <%= f.text_field :cooking_time, placeholder: "00", class: "text-center col-1 ml-5" %>分
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :製作金額, class: "col-sm-3 light mr-5" %>
            <%= f.text_field :cooking_cost, placeholder: "00", class: "text-center col-1 ml-5" %>円
          </div>
          <%= f.hidden_field :recipe_status, :value => "レシピなし" %>
          <div class="form-group col-10 text-center">
            <%= f.submit "投稿", class: "btn btn-success col-sm-2" %>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="mt-3 light">投稿詳細</h1>
  </div>

  <div class="row d-flex align-items-end mt-3">
    <div class="col-2"></div>
    <div class="col-8 card mx-auto p-2 light2">
      <div class="row d-flex align-items-end">
        <div class="col-3">
          <%= image_tag @post.user.get_user_image,  class:"user-img" %>
        </div>
        <div class="col-6">
          <h4>name：<%= @post.user.name %></h4>
        </div>
        <div class="col-3">
          <%= link_to "ユーザー詳細", user_path(@post.user.id) %>
        </div>
      </div>
    </div>
    <div class="col-2"></div>
  </div>

  <div class="row pt-3">
    <div class="col-1"></div>
    <div class="col-10 card mx-auto p-2 shadow-lg mt-5 w-90 border-radius: 300px light2">
      <%= image_tag @post.get_post_image, class:"show-img" %>

      <div class="row mt-4">
        <div class="col-3">
          投稿日時：<%= @post.created_at.strftime('%Y/%m/%d') %>
        </div>
        <div class="col-6"></div>
        <div class="col-3">
          <%#いいね機能%>
          <div id="favorite_btn_<%= @post.id %>">
            <%= render 'favorites/favorite', post: @post %>
          </div>
          <p>コメント<%= @post.comments.count %></p>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-3"></div>
        <h1 class="col-7 border-top border-bottom"><%= @post.post_name %></h1>
        <div class="col-2 d-flex align-items-end">
          <%#カレントユーザーの場合編集・削除リンク表示%>
          <% if @post.user == current_user %>
            <div class="ml-3">
              <%= link_to "編集", edit_post_path(@post) %>
            </div>
            <div class="ml-3">
              <%= link_to "削除", post_path(@post), method: :delete %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-3"></div>
        <h1 class="col-7">説明</h3>
        <div class="col-2"></div>
      </div>

      <div class="row mt-1">
        <div class="col-3"></div>
        <h3 class="col-7 border-top border-bottom"><%= @post.post_introduction %></h3>
        <div class="col-2"></div>
      </div>

      <div class="row mt-4">
        <div class="col-3"></div>
        <h3 class="col-7">ジャンル</h3>
        <div class="col-2"></div>
      </div>
      <div class="row mt-1">
        <div class="col-3"></div>
        <% @post.genres.each do |genre| %>
          <%= link_to genre_path(genre.id) do %>
            <p class="ml-3 badge badge-pill badge-primary light3"><%= genre.genre_name %></p>
          <% end %>
        <% end %>
      </div>

      <div class="row mt-4">
        <div class="col-3"></div>
        <h5 class="col-3">製作時間：<%= @post.cooking_time %>分</h5>
        <h5 class="col-3">製作金額：<%= @post.cooking_cost %>円</h5>
        <h5 class="col-3">
          <%#レシピが存在する場合レシピリンク・レシピが存在しなくカレントユーザーの場合レシピ追加リンク %>
          <% if @post.recipe_status_before_type_cast==0 %>
            <%= link_to "レシピ", post_recipe_path(@post.id) %>
          <% else %>
            <% if  @post.user == current_user %>
              <%= link_to "レシピ追加", new_post_recipe_path(@post.id) %>
            <% end %>
          <% end %>
        </h5>
      </div>
    </div>
    <div class="col-1"></div>
  </div>

  <div class="row mt-4">
    <div class="col-1"></div>
    <div class="col-10">
      <%= form_with model: [@post, @comment], local: false do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class:"col-10" %>
        <%= f.submit "送信する" %>
      <% end %>
    </div>
    <div class="col-1"></div>
  </div>

  <div class="row">
    <div class="col-1"></div>
    <div class="col-10">
      <div id="comment">
        <%= render 'comments/comment', post: @post %>
      </div>
    </div>
    <div class="col-1"></div>
  </div>
</div>