config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to =>"homes#top"
  resources :users, only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: :index do
      collection do
        delete :destroy_all
      end
    end

  end

  resources :posts, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :recipes, only: [:new,:show,:edit,:update,:create,:destroy]
  end

  get 'search' => 'posts#search'


  resources :genres, only: [:show]




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_genres, dependent: :destroy
  has_many :posts, through: :post_genres
end

app/models/meterial.rb
class Meterial < ApplicationRecord
  belongs_to :post

  #validates :meterial_name, presence: true
  #validates :quantity, presence: true
  validates_presence_of :meterial_name
  validates_presence_of :quantity

end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope->{order(created_at: :desc)}

  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_genres, dependent: :destroy
  has_many :genres, through: :post_genres
  has_many :notifications, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :meterials, dependent: :destroy
  accepts_nested_attributes_for :recipes, :meterials, allow_destroy: true

  enum recipe_status: { レシピあり: 0, レシピなし: 1 }

  validates :post_name, presence: true
  validates :post_image, presence: true

  before_save :attach_default_image, unless: :post_image_attached?

  #いいね
  def favorited?(user)
     favorites.where(user_id: user.id).exists?
  end

  #投稿画像
  def get_post_image
    post_image.variant(resize_to_limit: [500, 500]).processed
  end

  #通知機能
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "favorited"
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end

    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )

    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  private

  def post_image_attached?
    post_image.attached?
  end

  def attach_default_image
    file_path = Rails.root.join('app/assets/images/no_image1.jpg')
    post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :post
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :recipe_image
  belongs_to :post

  validates_presence_of :recipe

  before_save :attach_default_image, unless: :recipe_image_attached?


  def get_recipe_image
    recipe_image.variant(resize_to_limit: [300, 300]).processed
  end

  private

  def recipe_image_attached?
    recipe_image.attached?
  end

  def attach_default_image
    file_path = Rails.root.join('app/assets/images/no_image1.jpg')
    recipe_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #プロフィールイメージ
  has_one_attached :user_image

  has_many :posts, dependent: :destroy
  #いいね機能
  has_many :favorites, dependent: :destroy
  #コメント機能
  has_many :comments, dependent: :destroy
  #フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create

  before_save :attach_default_image, unless: :user_image_attached?

  #フォローする
  def follow(user_id)
    self.relationships.create!(followed_id: user_id)
  end
  #フォロー解除
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    self.followings.include?(user)
  end

  #プロフィールイメージ
  def get_user_image
    user_image.variant(resize_to_limit: [300, 300]).processed
  end

  #フォロー時の通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  private

  def user_image_attached?
    user_image.attached?
  end

  def attach_default_image
    file_path = Rails.root.join('app/assets/images/no_image1.jpg')
    user_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @posts = Post.order('id DESC').limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipies_helper.rb
module RecipiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white pt-2 pb-2">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-4">
        <h5>Sweets Home</h5>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm mb-0 pb-0">
  <nav class="navbar navbar-light p-0 light2">
    <div class="container">
      <a class="navbar-brand" href="/" data-turbolincks="false"><%= image_tag 'logo2.png', size: "200x50" %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        menu
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="row ml-0">
              <i class="far fa-bell mt-2 pt-1"></i>
              <%= link_to "お知らせ", user_notifications_path(current_user.id), class: 'nav-link text-dark ml-2' %>
              <% if unchecked_notifications.any? %>
                <div class="fa fa-circle mt-2 ml-2 pt-1" style="color: gold;"></div>
              <% end %>
            </li>
            <li class="row ml-0">
              <i class="fas fa-user-circle mt-2 pt-1"></i>
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark ml-2' %>
            </li>
            <li class="row ml-0">
              <i class="fas fa-pen-square mt-2 pt-1"></i>
              <%= link_to '新規投稿', new_post_path, class: 'nav-link text-dark ml-2' %>
            </li>
            <li class="row ml-0">
              <i class="fas fa-list-alt mt-2 pt-1"></i>
              <%= link_to '投稿一覧', posts_path, class: 'nav-link text-dark ml-2' %>
            </li>
            <li class="row ml-0">
              <i class="fas fa-sign-out-alt mt-2 pt-1" aria-hidden="true"></i>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark ml-2' %>
            </li>
          <% else %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetsHome</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload'%>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>